var express = require("express");
var router = express.Router();
const userApi = require("./user.api");
const blogApi = require("./blog.api");
const reactionApi = require("./reaction.api");
const authApi = require("./auth.api");
const reviewApi = require("./review.api");
const friendshipApi = require("./friendship.api");
router.use("/users", userApi);
router.use("/blogs", blogApi);
router.use("/reaction", reactionApi);
router.use("/auth", authApi);
router.use("/reviews", reviewApi);
router.use("/friends", friendshipApi);
module.exports = router;
